version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  rabbit-mq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbit-mq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./support/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

volumes:
  postgres-data:
  rabbitmq_data: