server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:disabled}
    port: ${RABBITMQ_PORT:0}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

com:
  luv2code:
    rabbitmq:
      exchange:
        topic:
          order: ecommerce.order.topic-exchange
      queue:
        created: order-created-queue
        failed: order-failed-queue
        confirmed: order-confirmed-queue
      routing-key:
        order:
          created: order.created
          failed: order.failed
          confirmed: order.confirmed